<?xml version="1.0" encoding="UTF-8"?><testrun duration="314" footerText="Generated by IntelliJ IDEA on 19-3-12 下午4:14" name="SpringBeanFactoryTest.test1">
    <count name="total" value="1"/>
    <count name="error" value="1"/>
    <config nameIsGenerated="true" configId="JUnit" name="SpringBeanFactoryTest.test1">
        <module name="spring-boot-bean"/>
        <extension name="coverage">
            <pattern>
                <option name="PATTERN" value="com.util.*"/>
                <option name="ENABLED" value="true"/>
            </pattern>
        </extension>
        <option name="PACKAGE_NAME" value="com.util"/>
        <option name="MAIN_CLASS_NAME" value="com.util.SpringBeanFactoryTest"/>
        <option name="METHOD_NAME" value="test1"/>
        <option name="TEST_OBJECT" value="method"/>
        <option name="VM_PARAMETERS"/>
        <option name="WORKING_DIRECTORY" value="$MODULE_DIR$"/>
    </config>
    <root name="SpringBeanFactoryTest" comment="com.util" location="java:suite://com.util.SpringBeanFactoryTest">
        <output type="stdout">bean初始化前执行
bean初始化后执行
bean初始化前执行
bean初始化后执行
2019-03-12 16:14:01.128  INFO 12964 --- [           main] com.util.SpringBeanFactoryTest           : Started SpringBeanFactoryTest in 8.756 seconds (JVM running for 10.278)
bean初始化前执行
bean初始化后执行
</output>
        <output type="stdout">Process finished with exit code -1
</output>
    </root>
    <test duration="314" locationUrl="java:test://com.util.SpringBeanFactoryTest/test1" name="SpringBeanFactoryTest.test1" status="error">
        <output type="stdout">2019-03-12 16:14:01.326  INFO 12964 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService &amp;#39;applicationTaskExecutor&amp;#39;
销毁
2019-03-12 16:14:01.447  WARN 12964 --- [           main] o.s.test.context.TestContextManager      : Caught exception while invoking &amp;#39;afterTestMethod&amp;#39; callback on TestExecutionListener [org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@64cd705f] for test method [public void com.util.SpringBeanFactoryTest.test1()] and test instance [com.util.SpringBeanFactoryTest@39266403]
java.lang.IllegalStateException: The ApplicationContext loaded for [[WebMergedContextConfiguration@61df66b6 testClass = SpringBeanFactoryTest, locations = &amp;#39;{}&amp;#39;, classes = &amp;#39;{class com.SpringBootBeanApplication}&amp;#39;, contextInitializerClasses = &amp;#39;[]&amp;#39;, activeProfiles = &amp;#39;{}&amp;#39;, propertySourceLocations = &amp;#39;{}&amp;#39;, propertySourceProperties = &amp;#39;{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}&amp;#39;, contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@6e0e048a, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@23e028a9, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@72b6cbcc, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@23faf8f2], resourceBasePath = &amp;#39;src/main/webapp&amp;#39;, contextLoader = &amp;#39;org.springframework.boot.test.context.SpringBootContextLoader&amp;#39;, parent = [null]]] is not active. This may be due to one of the following reasons: 1) the context was closed programmatically by user code; 2) the context was closed during parallel test execution either according to @DirtiesContext semantics or due to automatic eviction from the ContextCache due to a maximum cache size policy.
	at org.springframework.util.Assert.state(Assert.java:94) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:112) ~[spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener.afterTestMethod(WebDriverTestExecutionListener.java:42) ~[spring-boot-test-autoconfigure-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:443) ~[spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:94) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:na]
2019-03-12 16:14:01.448  WARN 12964 --- [           main] o.s.test.context.TestContextManager      : Caught exception while invoking &amp;#39;afterTestMethod&amp;#39; callback on TestExecutionListener [org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@a9cd3b1] for test method [public void com.util.SpringBeanFactoryTest.test1()] and test instance [com.util.SpringBeanFactoryTest@39266403]
java.lang.IllegalStateException: The ApplicationContext loaded for [[WebMergedContextConfiguration@61df66b6 testClass = SpringBeanFactoryTest, locations = &amp;#39;{}&amp;#39;, classes = &amp;#39;{class com.SpringBootBeanApplication}&amp;#39;, contextInitializerClasses = &amp;#39;[]&amp;#39;, activeProfiles = &amp;#39;{}&amp;#39;, propertySourceLocations = &amp;#39;{}&amp;#39;, propertySourceProperties = &amp;#39;{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}&amp;#39;, contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@6e0e048a, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@23e028a9, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@72b6cbcc, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@23faf8f2], resourceBasePath = &amp;#39;src/main/webapp&amp;#39;, contextLoader = &amp;#39;org.springframework.boot.test.context.SpringBootContextLoader&amp;#39;, parent = [null]]] is not active. This may be due to one of the following reasons: 1) the context was closed programmatically by user code; 2) the context was closed during parallel test execution either according to @DirtiesContext semantics or due to automatic eviction from the ContextCache due to a maximum cache size policy.
	at org.springframework.util.Assert.state(Assert.java:94) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:112) ~[spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener.afterTestMethod(MockRestServiceServerResetTestExecutionListener.java:41) ~[spring-boot-test-autoconfigure-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:443) ~[spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:94) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:na]
2019-03-12 16:14:01.450  WARN 12964 --- [           main] o.s.test.context.TestContextManager      : Caught exception while invoking &amp;#39;afterTestMethod&amp;#39; callback on TestExecutionListener [org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@67a20f67] for test method [public void com.util.SpringBeanFactoryTest.test1()] and test instance [com.util.SpringBeanFactoryTest@39266403]
java.lang.IllegalStateException: The ApplicationContext loaded for [[WebMergedContextConfiguration@61df66b6 testClass = SpringBeanFactoryTest, locations = &amp;#39;{}&amp;#39;, classes = &amp;#39;{class com.SpringBootBeanApplication}&amp;#39;, contextInitializerClasses = &amp;#39;[]&amp;#39;, activeProfiles = &amp;#39;{}&amp;#39;, propertySourceLocations = &amp;#39;{}&amp;#39;, propertySourceProperties = &amp;#39;{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}&amp;#39;, contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@6e0e048a, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@23e028a9, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@72b6cbcc, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@23faf8f2], resourceBasePath = &amp;#39;src/main/webapp&amp;#39;, contextLoader = &amp;#39;org.springframework.boot.test.context.SpringBootContextLoader&amp;#39;, parent = [null]]] is not active. This may be due to one of the following reasons: 1) the context was closed programmatically by user code; 2) the context was closed during parallel test execution either according to @DirtiesContext semantics or due to automatic eviction from the ContextCache due to a maximum cache size policy.
	at org.springframework.util.Assert.state(Assert.java:94) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:112) ~[spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener.afterTestMethod(ResetMocksTestExecutionListener.java:64) ~[spring-boot-test-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:443) ~[spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:94) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190) [spring-test-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:na]
</output>
        <output type="stderr">java.lang.IllegalStateException: The ApplicationContext loaded for [[WebMergedContextConfiguration@61df66b6 testClass = SpringBeanFactoryTest, locations = &amp;#39;{}&amp;#39;, classes = &amp;#39;{class com.SpringBootBeanApplication}&amp;#39;, contextInitializerClasses = &amp;#39;[]&amp;#39;, activeProfiles = &amp;#39;{}&amp;#39;, propertySourceLocations = &amp;#39;{}&amp;#39;, propertySourceProperties = &amp;#39;{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}&amp;#39;, contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@6e0e048a, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@23e028a9, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@72b6cbcc, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@23faf8f2], resourceBasePath = &amp;#39;src/main/webapp&amp;#39;, contextLoader = &amp;#39;org.springframework.boot.test.context.SpringBootContextLoader&amp;#39;, parent = [null]]] is not active. This may be due to one of the following reasons: 1) the context was closed programmatically by user code; 2) the context was closed during parallel test execution either according to @DirtiesContext semantics or due to automatic eviction from the ContextCache due to a maximum cache size policy.
&#13;
	at org.springframework.util.Assert.state(Assert.java:94)&#13;
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:112)&#13;
	at org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener.afterTestMethod(WebDriverTestExecutionListener.java:42)&#13;
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:443)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:94)&#13;
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)&#13;
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)&#13;
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)&#13;
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)&#13;
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)&#13;
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)&#13;
	Suppressed: java.lang.IllegalStateException: The ApplicationContext loaded for [[WebMergedContextConfiguration@61df66b6 testClass = SpringBeanFactoryTest, locations = &amp;#39;{}&amp;#39;, classes = &amp;#39;{class com.SpringBootBeanApplication}&amp;#39;, contextInitializerClasses = &amp;#39;[]&amp;#39;, activeProfiles = &amp;#39;{}&amp;#39;, propertySourceLocations = &amp;#39;{}&amp;#39;, propertySourceProperties = &amp;#39;{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}&amp;#39;, contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@6e0e048a, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@23e028a9, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@72b6cbcc, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@23faf8f2], resourceBasePath = &amp;#39;src/main/webapp&amp;#39;, contextLoader = &amp;#39;org.springframework.boot.test.context.SpringBootContextLoader&amp;#39;, parent = [null]]] is not active. This may be due to one of the following reasons: 1) the context was closed programmatically by user code; 2) the context was closed during parallel test execution either according to @DirtiesContext semantics or due to automatic eviction from the ContextCache due to a maximum cache size policy.&#13;
		at org.springframework.util.Assert.state(Assert.java:94)&#13;
		at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:112)&#13;
		at org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener.afterTestMethod(MockRestServiceServerResetTestExecutionListener.java:41)&#13;
		... 20 more&#13;
	Suppressed: java.lang.IllegalStateException: The ApplicationContext loaded for [[WebMergedContextConfiguration@61df66b6 testClass = SpringBeanFactoryTest, locations = &amp;#39;{}&amp;#39;, classes = &amp;#39;{class com.SpringBootBeanApplication}&amp;#39;, contextInitializerClasses = &amp;#39;[]&amp;#39;, activeProfiles = &amp;#39;{}&amp;#39;, propertySourceLocations = &amp;#39;{}&amp;#39;, propertySourceProperties = &amp;#39;{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}&amp;#39;, contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@6e0e048a, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@23e028a9, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@72b6cbcc, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@23faf8f2], resourceBasePath = &amp;#39;src/main/webapp&amp;#39;, contextLoader = &amp;#39;org.springframework.boot.test.context.SpringBootContextLoader&amp;#39;, parent = [null]]] is not active. This may be due to one of the following reasons: 1) the context was closed programmatically by user code; 2) the context was closed during parallel test execution either according to @DirtiesContext semantics or due to automatic eviction from the ContextCache due to a maximum cache size policy.&#13;
		at org.springframework.util.Assert.state(Assert.java:94)&#13;
		at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:112)&#13;
		at org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener.afterTestMethod(ResetMocksTestExecutionListener.java:64)&#13;
		... 20 more&#13;
</output>
    </test>
</testrun>
